### ISSUE TITLE
Set up the dbt project

### ISSUE THREAD

**Issue by Ruidozo** [Ruidozo/TFL-Accidents-Project#25]
Here’s a **task list** formatted for a GitHub issue. You can copy and paste it directly into an issue for tracking progress.

---

### 🚀 **Task List: Set Up dbt Locally for TFL Accidents Project**
**Issue:** Setting up dbt to work locally with a PostgreSQL container for data transformations.

---

### ✅ **1. Install dbt & Dependencies**
- [x] Install required packages:
  ```bash
  pip install dbt-core dbt-postgres psycopg2-binary dbt-extractor dbt-utils
  ```
- [x] Verify installation:
  ```bash
  dbt --version
  ```

---

### ✅ **2. Verify PostgreSQL Connection**
- [x] Check if PostgreSQL container is running:
  ```bash
  docker ps
  ```
- [x] Test PostgreSQL connection:
  ```bash
  psql -h localhost -p 5433 -U postgres -d postgres
  ```

---

### ✅ **3. Create & Configure `dbt_project.yml`**
- [ ] Create `dbt_project.yml`:
  ```bash
  touch dbt_project.yml
  ```
- [ ] Add the following configuration:
  ```yaml
  name: "tfl_accidents_project"
  version: "1.0"
  config-version: 2

  profile: "tfl_accidents_project"

  models:
    tfl_accidents_project:
      staging:
        +materialized: view
      core:
        +materialized: table
  ```

---

### ✅ **4. Initialize dbt Project**
- [x] Run:
  ```bash
  dbt init tfl_accidents_project
  ```

---

### ✅ **5. Configure `profiles.yml`**
- [x] Create `profiles.yml`:
  ```bash
  mkdir -p ~/.dbt
  touch ~/.dbt/profiles.yml
  ```
- [x] Add PostgreSQL configuration:
  ```yaml
  tfl_accidents_project:
    target: dev
    outputs:
      dev:
        type: postgres
        host: localhost
        user: postgres
        password: your_postgres_password
        port: 5433
        dbname: postgres
        schema: public
        threads: 4
  ```

---

### ✅ **6. Test dbt Connection**
- [x] Run:
  ```bash
  dbt debug
  ```
- [x] Ensure dbt returns a **successful connection** message.

---

### ✅ **7. Create Required Folders & Files**
- [x] Run:
  ```bash
  mkdir -p models/staging models/core
  touch models/schema.yml
  ```

---

### ✅ **8. Define the First Staging Model**
- [x] Create the file:
  ```bash
  touch models/staging/stg_accidents.sql
  ```
- [x] Add SQL logic:
  ```sql
  with source as (
      select * from {{ source('tfl_data', 'accidents') }}
  )
  select * from source
  ```

---

### ✅ **9. Run dbt Pipeline**
- [x] Run:
  ```bash
  dbt run
  ```
- [ ] Verify that the `stg_accidents` model is created in PostgreSQL.

---

### ✅ **10. Verify Everything**
- [x] Run:
  ```bash
  dbt test
  ```
- [x] Generate documentation:
  ```bash
  dbt docs generate
  ```
- [x] Ensure everything runs successfully.

---

### 🎯 **Next Steps After Setup**
Once the setup is completed, move to:
1️⃣ **Create Core Models (`accidents_summary.sql`)**  
2️⃣ **Define Transformations (normalize datetime, categorize severity, etc.)**  
3️⃣ **Run dbt Tests (`dbt test`)**  

---

#### 📌 **Reference**  
- PostgreSQL Docker container running on **port 5433**.  
- Ensure `localhost` is correctly used in `profiles.yml` or use `172.17.0.1` if needed.  

---

### 🔗 **Issue Tracking**  
- **Status:** _In Progress_ / _Completed_  
- **Assigned to:** _@your_username_  

---

Let me know if you need any modifications! 🚀
